### ISSUE TITLE
cannot run electron app on Mac

### ISSUE THREAD

**Issue by grexe** [davidibl/dmnmgr-client#13]
running `npm run electron:mac` seems to build just fine, but fails in the bundling step,
Complete log follows (using macOS Catalina 10.15.4 (19E287)):

```
❯ npm run electron:mac                                                       3m 28s

> dmnmgr-client@1.1.0 electron:mac /Users/gregor/Develop/dmnmgr-client
> npm run build-prod && electron-builder build --mac


> dmnmgr-client@1.1.0 build-prod /Users/gregor/Develop/dmnmgr-client
> ng build --prod

Compiling @angular/service-worker/config : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/animations/browser/testing : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling angular-split : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/service-worker : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {0} runtime-es2015.1eba213af0b233498d9d.js (runtime) 1.45 kB [entry] [rendered]
chunk {0} runtime-es5.1eba213af0b233498d9d.js (runtime) 1.45 kB [entry] [rendered]
chunk {2} polyfills-es2015.c3aba2a5bcbcef38d45a.js (polyfills) 36.1 kB [initial] [rendered]
chunk {3} polyfills-es5.b67ce26656233f1b1bb7.js (polyfills-es5) 129 kB [initial] [rendered]
chunk {1} main-es2015.5d1976f764a96ea4376f.js (main) 1.06 MB [initial] [rendered]
chunk {1} main-es5.5d1976f764a96ea4376f.js (main) 1.17 MB [initial] [rendered]
chunk {4} styles.e55f307317f513fccaa9.css (styles) 124 kB [initial] [rendered]
chunk {scripts} scripts.1ec598064b8585f5d21c.js (scripts) 583 kB [entry] [rendered]
Date: 2020-05-25T15:11:22.994Z - Hash: 9686588d5592b701dcb9 - Time: 77112ms


  • electron-builder  version=22.3.2 os=19.4.0
  • loaded configuration  file=/Users/gregor/Develop/dmnmgr-client/electron-builder.json
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=release/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=nodegit@0.26.5 platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=8.2.5 appOutDir=release/mac
  • downloading     url=https://github.com/electron/electron/releases/download/v8.2.5/electron-v8.2.5-darwin-x64.zip size=66 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v8.2.5/electron-v8.2.5-darwin-x64.zip duration=13.479s
  ⨯ Application entry file "main.js" in the "/Users/gregor/Develop/dmnmgr-client/release/mac/dmnmgr.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.  stackTrace=
                                                                                                                                                                                          Error: Application entry file "main.js" in the "/Users/gregor/Develop/dmnmgr-client/release/mac/dmnmgr.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
                                                                                                                                                                                              at error (/Users/gregor/Develop/dmnmgr-client/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:7:12)
                                                                                                                                                                                              at checkFileInArchive (/Users/gregor/Develop/dmnmgr-client/node_modules/app-builder-lib/src/asar/asarFileChecker.ts:33:11)
                                                                                                                                                                                              at MacPackager.checkFileInPackage (/Users/gregor/Develop/dmnmgr-client/node_modules/app-builder-lib/src/platformPackager.ts:402:7)
                                                                                                                                                                                              at MacPackager.sanityCheckPackage (/Users/gregor/Develop/dmnmgr-client/node_modules/app-builder-lib/src/platformPackager.ts:453:5)
                                                                                                                                                                                              at MacPackager.doPack (/Users/gregor/Develop/dmnmgr-client/node_modules/app-builder-lib/src/platformPackager.ts:242:5)
                                                                                                                                                                                              at MacPackager.pack (/Users/gregor/Develop/dmnmgr-client/node_modules/app-builder-lib/src/macPackager.ts:131:7)
                                                                                                                                                                                              at Packager.doBuild (/Users/gregor/Develop/dmnmgr-client/node_modules/app-builder-lib/src/packager.ts:444:9)
                                                                                                                                                                                              at executeFinally (/Users/gregor/Develop/dmnmgr-client/node_modules/builder-util/src/promise.ts:12:14)
                                                                                                                                                                                              at Packager._build (/Users/gregor/Develop/dmnmgr-client/node_modules/app-builder-lib/src/packager.ts:373:31)
                                                                                                                                                                                              at Packager.build (/Users/gregor/Develop/dmnmgr-client/node_modules/app-builder-lib/src/packager.ts:337:12)
                                                                                                                                                                                              at executeFinally (/Users/gregor/Develop/dmnmgr-client/node_modules/builder-util/src/promise.ts:12:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dmnmgr-client@1.1.0 electron:mac: `npm run build-prod && electron-builder build --mac`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dmnmgr-client@1.1.0 electron:mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gregor/.npm/_logs/2020-05-25T15_11_56_963Z-debug.log
~/Develop/dmnmgr-client master !2 ?1 ❯ node_modules/.bin/electron-rebuild                                         1m 57s
✔ Rebuild Complete
~/Develop/dmnmgr-client master !2 ?1 ❯ npm run rebuild

> dmnmgr-client@1.1.0 rebuild /Users/gregor/Develop/dmnmgr-client
> electron-rebuild.cmd

sh: electron-rebuild.cmd: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! dmnmgr-client@1.1.0 rebuild: `electron-rebuild.cmd`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the dmnmgr-client@1.1.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gregor/.npm/_logs/2020-05-25T15_16_04_594Z-debug.log
~/Develop/dmnmgr-client master !2 ?1 ❯ npm run rebuild:mac
npm ERR! missing script: rebuild:mac
npm ERR!
npm ERR! Did you mean this?
npm ERR!     rebuild

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gregor/.npm/_logs/2020-05-25T15_16_07_383Z-debug.log
~/Develop/dmnmgr-client master !2 ?1 ❯ ls /Users/gregor/Develop/dmnmgr-client/release/mac/dmnmgr.app/Contents/Resources/app.asar.unpacked
node_modules
~/Develop/dmnmgr-client master !2 ?1 ❯ ls /Users/gregor/Develop/dmnmgr-client/release/mac/dmnmgr.app/Contents/Resources/app.asar.unpacked/node_modules
nodegit
~/Develop/dmnmgr-client master !2 ?1 ❯ ls /Users/gregor/Develop/dmnmgr-client/release/mac/dmnmgr.app/Contents/Resources/app.asar.unpacked/node_modules
nodegit
~/Develop/dmnmgr-client master !2 ?1 ❯ ls /Users/gregor/Develop/dmnmgr-client/release/mac/dmnmgr.app/Contents/Resources/app.asar.unpacked/node_modules
nodegit
~/Develop/dmnmgr-client master !2 ?1 ❯ ls /Users/gregor/Develop/dmnmgr-client/release/mac/dmnmgr.app/Contents/Resources/app.asar.unpacked/node_modules/nodegit
HISTORY.md       bin              dist             lifecycleScripts utils
LICENSE          build            include          package.json     vendor
~/Develop/dmnmgr-client master !2 ?1 ❯ less /Users/gregor/.npm/_logs/2020-05-25T15_16_07_383Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'rebuild:mac'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.7.0
4 verbose stack Error: missing script: rebuild:mac
4 verbose stack
4 verbose stack Did you mean this?
4 verbose stack     rebuild
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:3
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
5 verbose cwd /Users/gregor/Develop/dmnmgr-client
6 verbose Darwin 19.4.0
7 verbose argv "/usr/local/Cellar/node/12.7.0/bin/node" "/usr/local/bin/npm" "run" "rebuild:mac"
8 verbose node v12.7.0
9 verbose npm  v6.14.4
10 error missing script: rebuild:mac
10 error
10 error Did you mean this?
10 error     rebuild
11 verbose exit [ 1, true ]
~/Develop/dmnmgr-client master !2 ?1 ❯ cat /Users/gregor/.npm/_logs/2020-05-25T15_11_56_963Z-debug.log                6s
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'electron:mac'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.7.0
4 verbose run-script [ 'preelectron:mac', 'electron:mac', 'postelectron:mac' ]
5 info lifecycle dmnmgr-client@1.1.0~preelectron:mac: dmnmgr-client@1.1.0
6 info lifecycle dmnmgr-client@1.1.0~electron:mac: dmnmgr-client@1.1.0
7 verbose lifecycle dmnmgr-client@1.1.0~electron:mac: unsafe-perm in lifecycle true
8 verbose lifecycle dmnmgr-client@1.1.0~electron:mac: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/gregor/Develop/dmnmgr-client/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/Users/gregor/go/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
9 verbose lifecycle dmnmgr-client@1.1.0~electron:mac: CWD: /Users/gregor/Develop/dmnmgr-client
10 silly lifecycle dmnmgr-client@1.1.0~electron:mac: Args: [ '-c', 'npm run build-prod && electron-builder build --mac' ]
11 silly lifecycle dmnmgr-client@1.1.0~electron:mac: Returned: code: 1  signal: null
12 info lifecycle dmnmgr-client@1.1.0~electron:mac: Failed to exec electron:mac script
13 verbose stack Error: dmnmgr-client@1.1.0 electron:mac: `npm run build-prod && electron-builder build --mac`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid dmnmgr-client@1.1.0
15 verbose cwd /Users/gregor/Develop/dmnmgr-client
16 verbose Darwin 19.4.0
17 verbose argv "/usr/local/Cellar/node/12.7.0/bin/node" "/usr/local/bin/npm" "run" "electron:mac"
18 verbose node v12.7.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error dmnmgr-client@1.1.0 electron:mac: `npm run build-prod && electron-builder build --mac`
22 error Exit status 1
23 error Failed at the dmnmgr-client@1.1.0 electron:mac script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by grexe** [comment]
there is a folder `/Users/gregor/Develop/dmnmgr-client/release/mac/dmnmgr.app/Contents/Resources/app.asar.unpacked` but that seems to be used to generate the bundle and only contains a single module `nodegit`

**Comment by davidibl** [comment]
@grexe 
I think I can solve this. Will push a solution by the end of the week.

**Comment by grexe** [comment]
I'm also willing to test this one:)

**Comment by davidibl** [comment]
Hey @grexe 
there is a branch named "fix_compilation_missing_mainjs". This should fix this problem. Can you test that on your mac?

Kind regards
David
